### ISSUE TITLE
输入法的 custom 配置做了一些更新

### ISSUE THREAD

**Issue by lewangdev** [Mark24Code/rime-auto-deploy#1]
### Changes

* 添加了模糊音的自定义配置文件 [rime_ice.custom.yaml](https://gist.github.com/lewangdev/f8ebbba24f464e915fb7d36857fcbbe5#file-rime_ice-custom-yaml)
* 修复了皮肤候选字的背景色

### Gist 地址
[https://gist.github.com/f8ebbba24f464e915fb7d36857fcbbe5.git](https://gist.github.com/lewangdev/f8ebbba24f464e915fb7d36857fcbbe5)

**Comment by Mark24Code** [comment]
Thanks your work.

https://github.com/Mark24Code/rime-auto-deploy/commit/0342265c6adb49fbf74b291e4b04b912b40ad013

Done ✅
