### ISSUE TITLE
麻烦问下快捷键如何设置？

### ISSUE THREAD

**Issue by andyrubin69** [Mark24Code/rime-auto-deploy#13]
请教一下：

1. 想把中英文切换             快捷键设置成：Shift ⇧键，即：通过 Shift  来快速切换中英文；「和搜狗输入法保持一致」
2. 想把英文大小写切换     快捷键设置成：中/英键，    即：通过 中/英  来快速切换英文大小写；「和搜狗输入法保持一致」

目前使用的机型是M1，以上两点，基于rime-auto-deploy，应该在哪个文件中进行配置才能生效。

麻烦大佬能指点一下，谢谢！

**Comment by Mark24Code** [comment]
可以网上查阅下如何配置（我懒得折腾就用默认的，研究得不太多）。

找到具体的配置项目，可以写在 rime-auto-deploy/custom 下具体的配置文件中。部署会一同复制到设置目录。
