### ISSUE TITLE
修改主题不生效

### ISSUE THREAD

**Issue by duan-1** [Mark24Code/rime-auto-deploy#14]
在修改了 `squirrel.custom.yaml` 后，执行脚本的手动模式的`Copy custom config` 后重新部署修改并生效，`squirrel.custom.yaml`文件倒是恢复到原来的样子

**Comment by Mark24Code** [comment]
手动模式 -> `Copy custom config` 是把 custom/*.custom.yaml 中的文件 覆盖到设置中。

所以在这里修改，和添加你自定义的文件。

**Comment by duan-1** [comment]
原来是我搞错了，我直接去改 `.local` 目录下的 yaml 文件，应该是改下载的主题目录里面的 yaml 文件
