### ISSUE TITLE
安装不上rime

### ISSUE THREAD

**Issue by Zhaojjjjjj** [Mark24Code/rime-auto-deploy#17]
=== Rime Deploy ====
[01] Install rime        	  done
[02] Backup rime config  	  done
[03] Clone config        	  done
[04] Copy custom config  	  done

Tips: When finished all jobs. You need to do follow:
1) Restart system.
2) open Rime input method setting pane and click DEPLOY button.
Enjoy~ 🍻
more info:
Config path: ~/Library/Rime/

安装步骤提示这个以后，重启系统，输入法哪里还是没有rime

**Comment by Mark24Code** [comment]
MacOS13之前，添加完输入法是会自动弹出设置框。

MacOS13之后好像不会弹出来了，需要自己手动的添加 Rime 输入法

设置 - 键盘 - 输入法 （编辑）- 弹出框左下角 + 号添加启用 Rime


![Uploading 截屏2024-02-28 11.04.26.png…]()
