### ISSUE TITLE
请问如何调整输入栏的高度

### ISSUE THREAD

**Issue by NeoLyu** [Mark24Code/rime-auto-deploy#21]
<img width="578" alt="Snipaste_2024-03-14_14-02-33" src="https://github.com/Mark24Code/rime-auto-deploy/assets/12368724/602d3ccc-d0dc-4e14-b61e-2c15074859e0">

如图，把字号从21调整为16后发现下面的留白太多了，试了好些方法都不行，望不吝赐教，感激不尽。

**Comment by NeoLyu** [comment]
尝试修改候选框字体后已经解决了，谢谢。

**Comment by Mark24Code** [comment]
👍 @NeoLyu
