### ISSUE TITLE
更新失败Rime Config seems broken. You may delete the directory.

### ISSUE THREAD

**Issue by zzh068** [Mark24Code/rime-auto-deploy#23]
<img width="550" alt="image" src="https://github.com/Mark24Code/rime-auto-deploy/assets/128816176/4a6f0256-7039-488b-8c64-55bb91eac5af">

你好！请问这是什么导致的更新失败？目前只是git clone之后，执行过一次auto install的脚本

以及没有看到雾凇拼音有安装成功？
<img width="716" alt="image" src="https://github.com/Mark24Code/rime-auto-deploy/assets/128816176/4a58b5ad-38db-4a99-a7b7-04e6404b8b5f">

**Comment by Mark24Code** [comment]
执行一遍自动安装试试。它会备份，然后重新下载一份

报错应该是，应该是你删除雾凇的仓库里面的 .git 目录

**Comment by Mark24Code** [comment]
一周没回复，我先关掉了。如果有后续再打开。
