### ISSUE TITLE
linux ibus rime skin

### ISSUE THREAD

**Issue by touero** [Mark24Code/rime-auto-deploy#24]
查询了已关闭的issue， 还是不知道如何设置Ubuntu ibus rime的皮肤

**Comment by Mark24Code** [comment]
没有找到覆盖皮肤的办法。找到了欢迎PR

**Comment by ponymushama** [comment]
> 没有找到覆盖皮肤的办法。找到了欢迎 PR

作者大大，所以目前 Linux 上的 Rime 是无法修改皮肤的吗？

**Comment by Mark24Code** [comment]
> > 没有找到覆盖皮肤的办法。找到了欢迎 PR
> 
> 作者大大，所以目前 Linux 上的 Rime 是无法修改皮肤的吗？

测试下来是这样的。

**Comment by KamijoToma** [comment]
安装这个GNOME Extension或许能够帮到你：Customize IBus。里面提供了自定义css的选项，同时内置了两款皮肤
