### ISSUE TITLE
README.md 输入法皮肤来源链接指向网络钓鱼

### ISSUE THREAD

**Issue by gandli** [Mark24Code/rime-auto-deploy#27]
> 集成 20款 输入法皮肤, 来源 https://ssnhd.com/2022/01/11/rime-skin/ 包括微信皮肤

![image](https://github.com/Mark24Code/rime-auto-deploy/assets/85359251/ee46bffa-cfe5-4a74-b793-770b5bcdf595)

**Comment by Mark24Code** [comment]
防不胜防。链接来自于网络上一个分享的 技术博主，可能他的域名过期了。现在移除了这个链接。非常感谢！
