### ISSUE TITLE
[bug] 模糊音正则匹配导致 cou 无法输入

### ISSUE THREAD

**Issue by love98ooo** [Mark24Code/rime-auto-deploy#29]
./custom/rime_ice.custom.yaml 文件中

```
- derive/([rtsdghkzc])o(u|ng)$/$1o/
```

导致 cou 如 (凑) 无法输入

**Comment by Mark24Code** [comment]
看起来可以哎

<img width="218" alt="截屏2024-10-09 15 25 02" src="https://github.com/user-attachments/assets/3154bbac-117e-4729-850c-21b3ea3d2f47">

**Comment by love98ooo** [comment]
按照正则的逻辑，输入 `cou` 的时候应该会被匹配成 `co`，也可能是我配置文件其他地方和这里有冲突，那我先把 issue 关了
