### ISSUE TITLE
内存占用过高

### ISSUE THREAD

**Issue by luxixing** [Mark24Code/rime-auto-deploy#3]
之前使用了一阵子最后，mac下系统的内存占用超过了8G， 迫不得已停用了，
有人发推文也说过内存占用高的问题， 说是要替换更新rime.lua 不知道是否解决了？

**Comment by Mark24Code** [comment]
下载最新版本的这个脚本(v3.2.0新增更新模式)，使用更新模式，更新rime config即可
(上游的配置库修复了内存泄露的问题)。
