### ISSUE TITLE
咨询一下你截图中使用的字体是哪个我看着蛮好看的，谢谢哈

### ISSUE THREAD

**Issue by ansnail** [Mark24Code/rime-auto-deploy#30]
如题

**Comment by Mark24Code** [comment]
Mac OS 下：

苹方-简体
PingFangSC

<img width="1112" alt="截屏2024-11-20 11 27 28" src="https://github.com/user-attachments/assets/d3aa910f-3e20-4761-86e9-7e2cd9dc69e9">
