### ISSUE TITLE
愿意捐赠你一杯咖啡奶茶，有偿咨询

### ISSUE THREAD

**Issue by Newfund88** [Mark24Code/rime-auto-deploy#31]
[
<img width="864" alt="截屏2024-12-06 05 39 57" src="https://github.com/user-attachments/assets/595ec2f0-a23f-4e9c-b764-0923a18fe0e2">
](url)

你好能否看看为何 macbook版本设置 候选词 横向显示一直都没法 横向显示

使用的你的代码 克隆复制的  但是一直出错 怎么都没法 横向显示，愿意捐赠你一杯咖啡奶茶，有偿咨询， 还请看看 为何一直没法显示横痃候选词显示
<img width="864" alt="截屏2024-12-06 05 39 57" src="https://github.com/user-attachments/assets/cd86d1cc-73f5-488b-bf99-ebfa7e4d133b">

**Comment by Mark24Code** [comment]
qq交流群：761103715
