### ISSUE TITLE
Linux 上有办法使用这个皮肤吗

### ISSUE THREAD

**Issue by spphinslove** [Mark24Code/rime-auto-deploy#6]
fcitx5-rime的 安装后没有皮肤吧

**Comment by Mark24Code** [comment]
Linux上 fcitx、ibus、fcitx5 都不一样。rime的皮肤配置，没有在各自的输入法平台生效（可能rime没做吧）。

**Comment by spphinslove** [comment]
> Linux上 fcitx、ibus、fcitx5 都不一样。rime的皮肤配置，没有在各自的输入法平台生效（可能rime没做吧）。

我搜索了一下 fcitx5没什么好看的皮肤。。。

**Comment by Mark24Code** [comment]
我直接默认皮肤。 :D
