### ISSUE TITLE
单字母拼音（每个字只写一个字母），没有显示候选

### ISSUE THREAD

**Issue by zhangciwu** [Mark24Code/rime-auto-deploy#7]
比如“wkk”（我看看），就没有候选窗口显示，必须输入“wokankan”
我感觉应该是某个配置项可以选，但是我没找到
（我不需要双拼，只需要拼音）

不知道可否指出具体是什么配置项

**Comment by zhangciwu** [comment]
<img width="747" alt="image" src="https://github.com/Mark24Code/rime-auto-deploy/assets/3340597/35b2e913-b892-4d56-a32c-dc91136f057a">
这部分打开即可

**Comment by Mark24Code** [comment]
最近比较忙，才看到。感谢捐赠 @zhangciwu  🌹
