### ISSUE TITLE
只有三款皮肤

### ISSUE THREAD

**Issue by wtfsb19** [Mark24Code/rime-auto-deploy#8]
打开配置文件`weasel.custom,yaml`，里面只有三款皮肤
![image](https://github.com/Mark24Code/rime-auto-deploy/assets/70636030/cd5be703-f288-4943-88f7-5751c71c2eb3)

**Comment by Mark24Code** [comment]
Windows 的 Rime 好像已经停止开发了。

Rime 的主题在 Windows 上表现很弱。这里只给了简单的。
Rime 在Linux上定制会被覆盖。在MacOS上表现比较好，定制属性生效得多。

**Comment by trace1729** [comment]
在 Linux 上会被覆盖的意思是，在 Linux 下没法对输入法更换皮肤吗

**Comment by trace1729** [comment]
> Windows 的 Rime 好像已经停止开发了。
> 
> Rime 的主题在 Windows 上表现很弱。这里只给了简单的。 Rime 在Linux上定制会被覆盖。在MacOS上表现比较好，定制属性生效得多。

在 Linux 上会被覆盖的意思是，在 Linux 下没法对输入法更换皮肤吗？

**Comment by Mark24Code** [comment]
我在 Debian、Ubuntu 上测试，无法覆盖Linux下的皮肤。

@trace1729
