### ISSUE TITLE
雾凇拼音用这个自动更新脚本后没有同步cn_dicts、en_dicts、opencc、Lua和other等文件夹

### ISSUE THREAD

**Issue by Jreen** [Mark24Code/rime-auto-deploy#9]
rt

**Comment by Mark24Code** [comment]
<img width="640" alt="截屏2023-09-07 10 24 56" src="https://github.com/Mark24Code/rime-auto-deploy/assets/7592004/dcaf2e7b-570e-4986-aa3d-91edb9e75f14">

可能是因为你的网络问题。没有完整的下载成功。

目前我看起来，整个仓库是完整同步过来的。

可以进入安装界面选择：

[3]UpgradeMode -> [2] Upgrade rime config  

来手动同步： 雾凇拼音
